### ISSUE TITLE
MELPA installs empty files

### ISSUE THREAD

**Issue by deerpig** [xuchunyang/grab-x11-link#3]
When installing from MELPA it just installs empty files -- no code.  I copied the file from the repo and it all works nicely.   But it would be good to be able to install from MELPA.

**Comment by xuchunyang** [comment]
Not sure what's the cause (maybe your network issue?). Anyway, Melpa does provide grab-x-link and it is not empty, see https://melpa.org/#/grab-x-link

**Comment by deerpig** [comment]
The files installed but the .el file was empty and the .elc file had a comment that it compiled.  It could just be a MELPA glitch.  If it's still working for you it must be a one off problem.  

Thanks and hope you have a good morning!

**Comment by xuchunyang** [comment]
> If it's still working for you it must be a one off problem.

Yes, it works here, I just tried.
